### ISSUE TITLE
Tambah kolom keterangan dan status pada tabel barang masuk.

### ISSUE THREAD

**Issue by paley777** [paley777/mypos#25]

**Comment by paley777** [comment]
@DemuraAIdev 
penambahan kolom satu lagi
Status
isinya cuman dua
Hutang atau Lunas

kalau lunas yaudah
kalau hutang berikan tombol Lunaskan di kolom aksi di halaman indexnya.

**Comment by DemuraAIdev** [comment]
Lah bukannya harus di table piutang @paley777

**Comment by paley777** [comment]
bagi barang masuk juga, penambahan kolom

**Comment by DemuraAIdev** [comment]
bukan, tapi tombol "lunaskan" nya, katanya di hapus aja biar semua lunaskan tu cuman di tabel piutang

**Comment by paley777** [comment]
Ini beda hal, ikutin aja
